/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./src/**/*.{ts,tsx}"],
	presets: [require("nativewind/preset")],
	theme: {
		extend: {
			colors: {
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				border: "rgba(255, 255, 255, 0.12)",
				input: "rgba(255, 255, 255, 0.15)",
				ring: "hsl(var(--ring))",
				hydro: {
					primary: "#4CAF50",
					"primary-light": "#66BB6A",
					"primary-dark": "#388E3C",
					"primary-deep": "#2E7D32",
					accent: "#76FF03",
					bg: "#0D2818",
					"bg-mid": "#1A3C28",
					"bg-light": "#264D38",
					surface: "rgba(20, 60, 35, 0.85)",
					"surface-variant": "rgba(255, 255, 255, 0.06)",
					glass: "rgba(255, 255, 255, 0.08)",
					"glass-hover": "rgba(255, 255, 255, 0.12)",
					error: "#EF5350",
					"error-light": "rgba(239, 83, 80, 0.15)",
					warning: "#FFB74D",
					"warning-light": "rgba(255, 183, 77, 0.15)",
					success: "#66BB6A",
					"success-light": "rgba(102, 187, 106, 0.15)",
					info: "#42A5F5",
					"info-light": "rgba(66, 165, 245, 0.15)",
					nft: "#66BB6A",
					dft: "#42A5F5",
					"dutch-bucket": "#FFB74D",
					kratky: "#CE93D8",
					snap: "#80DEEA",
				},
			},
			borderRadius: {
				xl: "12px",
				"2xl": "16px",
				"3xl": "20px",
			},
			fontSize: {
				xs: ["11px", { lineHeight: "16px" }],
				sm: ["13px", { lineHeight: "18px" }],
				base: ["15px", { lineHeight: "22px" }],
				lg: ["17px", { lineHeight: "24px" }],
				xl: ["20px", { lineHeight: "26px" }],
				"2xl": ["24px", { lineHeight: "30px" }],
				"3xl": ["32px", { lineHeight: "36px" }],
			},
		},
	},
	plugins: [],
};
