"""Seed data for crop guide. Top 20 PH hydroponic crops (bilingual)."""

from app.modules.crops.schema import CropCategory

CROP_SEED = [
    {
        "name_en": "Pechay",
        "name_tl": "Pechay",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 6.0,
        "ph_max": 7.0,
        "ec_min": 1.4,
        "ec_max": 2.0,
        "days_to_harvest_min": 25,
        "days_to_harvest_max": 35,
        "typical_yield_grams": 120.0,
        "sunlight_hours": "10-12",
        "temperature_day_c": "22-28",
        "temperature_night_c": "16-20",
        "common_issues": "Bolting in heat; tip burn from Ca deficiency",
        "harvest_indicator": "Leaves ~15cm, firm heads",
        "image_key": "pechay_crop.png",
        "source": "DA-BPI, Kai farm calibration",
    },
    {
        "name_en": "Lettuce (Romaine)",
        "name_tl": "Letsugas (Romaine)",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT",
        "ph_min": 5.8,
        "ph_max": 6.2,
        "ec_min": 1.2,
        "ec_max": 1.8,
        "days_to_harvest_min": 30,
        "days_to_harvest_max": 45,
        "typical_yield_grams": 200.0,
        "sunlight_hours": "10-14",
        "temperature_day_c": "18-24",
        "temperature_night_c": "12-18",
        "common_issues": "Tip burn; bolting above 27C",
        "harvest_indicator": "Tight inner heart forms",
        "image_key": "lettuce_crop.png",
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Lettuce (Butterhead)",
        "name_tl": "Letsugas (Butterhead)",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 5.8,
        "ph_max": 6.2,
        "ec_min": 1.0,
        "ec_max": 1.6,
        "days_to_harvest_min": 28,
        "days_to_harvest_max": 40,
        "typical_yield_grams": 180.0,
        "sunlight_hours": "10-14",
        "temperature_day_c": "18-24",
        "temperature_night_c": "12-18",
        "common_issues": "Tip burn at high EC",
        "harvest_indicator": "Soft loose head ~18cm",
        "image_key": "lettuce_crop.png",
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Lettuce (Loose-leaf)",
        "name_tl": "Letsugas (Loose-leaf)",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 5.8,
        "ph_max": 6.2,
        "ec_min": 1.0,
        "ec_max": 1.4,
        "days_to_harvest_min": 21,
        "days_to_harvest_max": 30,
        "typical_yield_grams": 150.0,
        "sunlight_hours": "10-14",
        "temperature_day_c": "18-26",
        "temperature_night_c": "14-20",
        "common_issues": "Bolting in heat",
        "harvest_indicator": "Leaves 12-15cm",
        "image_key": "lettuce_crop.png",
        "source": "DA-ATI",
    },
    {
        "name_en": "Kangkong",
        "name_tl": "Kangkong",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,Kratky,SNAP",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 1.4,
        "ec_max": 2.2,
        "days_to_harvest_min": 25,
        "days_to_harvest_max": 35,
        "typical_yield_grams": 150.0,
        "sunlight_hours": "8-12",
        "temperature_day_c": "25-32",
        "temperature_night_c": "20-25",
        "common_issues": "Leaf miners; yellowing from N deficiency",
        "harvest_indicator": "Stems 20cm, cut-and-come-again",
        "image_key": "kangkong_crop.png",
        "source": "DA-BPI",
    },
    {
        "name_en": "Mustard Greens",
        "name_tl": "Mustasa",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 6.0,
        "ph_max": 7.0,
        "ec_min": 1.2,
        "ec_max": 2.0,
        "days_to_harvest_min": 30,
        "days_to_harvest_max": 40,
        "typical_yield_grams": 160.0,
        "sunlight_hours": "10-12",
        "temperature_day_c": "20-26",
        "temperature_night_c": "15-20",
        "common_issues": "Flea beetles; bolting",
        "harvest_indicator": "Leaves 20-25cm",
        "image_key": "mustard_greens_crop.png",
        "source": "DA-ATI",
    },
    {
        "name_en": "Arugula",
        "name_tl": "Arugula",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 6.0,
        "ph_max": 7.0,
        "ec_min": 0.8,
        "ec_max": 1.4,
        "days_to_harvest_min": 20,
        "days_to_harvest_max": 30,
        "typical_yield_grams": 80.0,
        "sunlight_hours": "8-12",
        "temperature_day_c": "18-24",
        "temperature_night_c": "12-18",
        "common_issues": "Rapid bolting >26C",
        "harvest_indicator": "Leaves 10-12cm",
        "image_key": None,
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Spinach",
        "name_tl": "Spinach",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT",
        "ph_min": 6.0,
        "ph_max": 7.0,
        "ec_min": 1.8,
        "ec_max": 2.3,
        "days_to_harvest_min": 30,
        "days_to_harvest_max": 45,
        "typical_yield_grams": 120.0,
        "sunlight_hours": "10-12",
        "temperature_day_c": "16-22",
        "temperature_night_c": "10-16",
        "common_issues": "Rapid bolting >24C",
        "harvest_indicator": "Leaves 15cm",
        "image_key": None,
        "source": "DA-ATI",
    },
    {
        "name_en": "Basil",
        "name_tl": "Balanoy",
        "category": CropCategory.herb,
        "recommended_setups": "DFT,NFT,Kratky,DutchBucket",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 1.0,
        "ec_max": 1.6,
        "days_to_harvest_min": 30,
        "days_to_harvest_max": 60,
        "typical_yield_grams": 100.0,
        "sunlight_hours": "10-14",
        "temperature_day_c": "22-28",
        "temperature_night_c": "18-22",
        "common_issues": "Fusarium wilt; flowering reduces flavor",
        "harvest_indicator": "Pinch above node, before flowering",
        "image_key": "basil_crop.png",
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Mint",
        "name_tl": "Yerba buena",
        "category": CropCategory.herb,
        "recommended_setups": "DFT,Kratky,DutchBucket",
        "ph_min": 6.0,
        "ph_max": 7.0,
        "ec_min": 1.6,
        "ec_max": 2.0,
        "days_to_harvest_min": 40,
        "days_to_harvest_max": 70,
        "typical_yield_grams": 80.0,
        "sunlight_hours": "8-12",
        "temperature_day_c": "20-26",
        "temperature_night_c": "15-20",
        "common_issues": "Spreads aggressively; rust",
        "harvest_indicator": "Stems 15-20cm",
        "image_key": None,
        "source": "DA-ATI",
    },
    {
        "name_en": "Cilantro",
        "name_tl": "Wansoy",
        "category": CropCategory.herb,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 6.0,
        "ph_max": 7.0,
        "ec_min": 1.2,
        "ec_max": 1.8,
        "days_to_harvest_min": 30,
        "days_to_harvest_max": 45,
        "typical_yield_grams": 60.0,
        "sunlight_hours": "8-10",
        "temperature_day_c": "18-24",
        "temperature_night_c": "12-18",
        "common_issues": "Rapid bolting in heat",
        "harvest_indicator": "Leaves before flowering",
        "image_key": None,
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Parsley",
        "name_tl": "Parsley",
        "category": CropCategory.herb,
        "recommended_setups": "DFT,NFT,Kratky",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 1.8,
        "ec_max": 2.2,
        "days_to_harvest_min": 60,
        "days_to_harvest_max": 90,
        "typical_yield_grams": 80.0,
        "sunlight_hours": "8-12",
        "temperature_day_c": "18-24",
        "temperature_night_c": "12-18",
        "common_issues": "Slow germination",
        "harvest_indicator": "Outer stems 15cm",
        "image_key": None,
        "source": "DA-ATI",
    },
    {
        "name_en": "Tomato (Cherry)",
        "name_tl": "Kamatis (Cherry)",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 2.0,
        "ec_max": 3.5,
        "days_to_harvest_min": 70,
        "days_to_harvest_max": 100,
        "typical_yield_grams": 1500.0,
        "sunlight_hours": "12-14",
        "temperature_day_c": "22-28",
        "temperature_night_c": "16-20",
        "common_issues": "BER (Ca), blight, whitefly",
        "harvest_indicator": "Fruit fully red, firm",
        "image_key": "tomatoes_crop.png",
        "source": "DA-BPI, Kai farm",
    },
    {
        "name_en": "Bell Pepper",
        "name_tl": "Bell Pepper",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket",
        "ph_min": 5.8,
        "ph_max": 6.5,
        "ec_min": 2.0,
        "ec_max": 3.0,
        "days_to_harvest_min": 80,
        "days_to_harvest_max": 110,
        "typical_yield_grams": 1200.0,
        "sunlight_hours": "12-14",
        "temperature_day_c": "22-28",
        "temperature_night_c": "18-22",
        "common_issues": "BER; aphids; slow early growth",
        "harvest_indicator": "Full-size, color change",
        "image_key": "bell_peppers_crop.png",
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Cucumber",
        "name_tl": "Pipino",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 1.7,
        "ec_max": 2.5,
        "days_to_harvest_min": 50,
        "days_to_harvest_max": 70,
        "typical_yield_grams": 2000.0,
        "sunlight_hours": "12-14",
        "temperature_day_c": "22-30",
        "temperature_night_c": "18-22",
        "common_issues": "Powdery mildew; spider mites",
        "harvest_indicator": "Fruit 18-22cm, firm",
        "image_key": "cucumbers_crop.png",
        "source": "DA-BPI",
    },
    {
        "name_en": "Strawberry",
        "name_tl": "Strawberry",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket,NFT",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 1.2,
        "ec_max": 2.0,
        "days_to_harvest_min": 90,
        "days_to_harvest_max": 120,
        "typical_yield_grams": 250.0,
        "sunlight_hours": "10-12",
        "temperature_day_c": "18-24",
        "temperature_night_c": "10-16",
        "common_issues": "Root rot; poor fruit set in heat",
        "harvest_indicator": "Full red color",
        "image_key": None,
        "source": "DOST-PCAARRD",
    },
    {
        "name_en": "Okra",
        "name_tl": "Okra",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket",
        "ph_min": 6.0,
        "ph_max": 6.8,
        "ec_min": 2.0,
        "ec_max": 2.5,
        "days_to_harvest_min": 50,
        "days_to_harvest_max": 65,
        "typical_yield_grams": 500.0,
        "sunlight_hours": "10-14",
        "temperature_day_c": "24-32",
        "temperature_night_c": "20-25",
        "common_issues": "Aphids; tough pods if over-mature",
        "harvest_indicator": "Pods 7-10cm, tender",
        "image_key": None,
        "source": "DA-BPI",
    },
    {
        "name_en": "Ampalaya",
        "name_tl": "Ampalaya",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket",
        "ph_min": 6.0,
        "ph_max": 6.8,
        "ec_min": 2.0,
        "ec_max": 2.8,
        "days_to_harvest_min": 60,
        "days_to_harvest_max": 80,
        "typical_yield_grams": 800.0,
        "sunlight_hours": "10-14",
        "temperature_day_c": "24-32",
        "temperature_night_c": "20-25",
        "common_issues": "Fruit fly; needs trellising",
        "harvest_indicator": "Fruit 15-20cm, firm green",
        "image_key": "ampalaya_crop.png",
        "source": "DA-BPI",
    },
    {
        "name_en": "Eggplant",
        "name_tl": "Talong",
        "category": CropCategory.fruiting,
        "recommended_setups": "DutchBucket",
        "ph_min": 5.5,
        "ph_max": 6.5,
        "ec_min": 2.0,
        "ec_max": 3.0,
        "days_to_harvest_min": 70,
        "days_to_harvest_max": 100,
        "typical_yield_grams": 1500.0,
        "sunlight_hours": "12-14",
        "temperature_day_c": "24-30",
        "temperature_night_c": "18-22",
        "common_issues": "Fruit borer; Ca deficiency",
        "harvest_indicator": "Shiny skin, firm",
        "image_key": "eggplant_crop.png",
        "source": "DA-BPI",
    },
    {
        "name_en": "Celery",
        "name_tl": "Kintsay",
        "category": CropCategory.leafy,
        "recommended_setups": "DFT,NFT",
        "ph_min": 6.0,
        "ph_max": 6.8,
        "ec_min": 1.8,
        "ec_max": 2.4,
        "days_to_harvest_min": 90,
        "days_to_harvest_max": 140,
        "typical_yield_grams": 300.0,
        "sunlight_hours": "8-12",
        "temperature_day_c": "16-22",
        "temperature_night_c": "10-16",
        "common_issues": "Slow, Ca-sensitive",
        "harvest_indicator": "Stems 20cm",
        "image_key": None,
        "source": "DOST-PCAARRD",
    },
]
