// This file is auto-generated by @hey-api/openapi-ts

export type ActivitiesPublic = {
    data: Array<ActivityPublic>;
    count: number;
};

export type ActivityPublic = {
    id: string;
    user_id: string;
    action_type: ActivityType;
    target_type?: (TargetType | null);
    target_id?: (string | null);
    summary: string;
    meta?: ({
    [key: string]: unknown;
} | null);
    created_at: string;
};

export type ActivityType = 'setup_created' | 'setup_archived' | 'setup_unarchived' | 'setup_deleted' | 'batch_created' | 'batch_archived' | 'batch_deleted' | 'batch_transition' | 'batch_harvest' | 'inventory_created' | 'inventory_restocked' | 'inventory_consumed' | 'inventory_adjusted' | 'inventory_deleted' | 'produce_created' | 'produce_movement' | 'sale_recorded' | 'sale_deleted' | 'overhead_added';

export type BatchAllocateSlots = {
    slots_used: number;
    seeds_per_slot: number;
};

export type BatchCreate = {
    setup_id: string;
    crop_guide_id?: (string | null);
    variety_name: string;
    slots_used: number;
    seeds_per_slot: number;
    notes?: (string | null);
    started_at?: (string | null);
    seed_inventory_item_id: string;
};

export type BatchDetail = {
    setup_id: string;
    crop_guide_id?: (string | null);
    variety_name: string;
    initial_count: number;
    slots_used?: (number | null);
    seeds_per_slot?: (number | null);
    notes?: (string | null);
    seed_inventory_item_id?: (string | null);
    id: string;
    owner_id: string;
    started_at: string;
    archived_at?: (string | null);
    legacy?: boolean;
    seed_cost?: (number | null);
    state_counts?: Array<BatchStateCountPublic>;
    recent_transitions?: Array<BatchTransitionPublic>;
};

export type BatchesPublic = {
    data: Array<BatchPublic>;
    count: number;
};

export type BatchHarvestCreate = {
    weight_grams: number;
    count: number;
    notes?: (string | null);
    harvested_at?: (string | null);
};

export type BatchHarvestPublic = {
    id: string;
    weight_grams: number;
    count: number;
    harvested_at: string;
    notes?: (string | null);
};

export type BatchPublic = {
    setup_id: string;
    crop_guide_id?: (string | null);
    variety_name: string;
    initial_count: number;
    slots_used?: (number | null);
    seeds_per_slot?: (number | null);
    notes?: (string | null);
    seed_inventory_item_id?: (string | null);
    id: string;
    owner_id: string;
    started_at: string;
    archived_at?: (string | null);
    legacy?: boolean;
    seed_cost?: (number | null);
};

export type BatchStateCountPublic = {
    milestone_code: Milestone;
    count: number;
    updated_at: string;
};

export type BatchTransitionCreate = {
    from_milestone: Milestone;
    to_milestone: Milestone;
    count: number;
    notes?: (string | null);
    photo_url?: (string | null);
    occurred_at?: (string | null);
};

export type BatchTransitionPublic = {
    id: string;
    from_milestone: Milestone;
    to_milestone: Milestone;
    count: number;
    occurred_at: string;
    notes?: (string | null);
    photo_url?: (string | null);
};

export type BatchUpdate = {
    setup_id?: (string | null);
    variety_name?: (string | null);
    crop_guide_id?: (string | null);
    notes?: (string | null);
    started_at?: (string | null);
    archived_at?: (string | null);
};

export type Body_hydro_common_photo_upload = {
    /**
     * e.g. setup, batch
     */
    scope: string;
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatRequest = {
    message: string;
};

export type ChatResponse = {
    answer: string;
    language: string;
    citations: Array<{
        [key: string]: unknown;
    }>;
    messages_used: number;
};

export type CheckoutRequest = {
    target_tier: UserTier;
    billing_cycle?: 'monthly' | 'yearly';
};

export type billing_cycle = 'monthly' | 'yearly';

export type CheckoutResponse = {
    checkout_url: string;
    amount_php: number;
    billing_cycle: string;
};

/**
 * Monthly climate normals for a (lat, lon, month) point.
 */
export type ClimateNormals = {
    provider: string;
    lat: number;
    lon: number;
    month: number;
    air_temp_c_avg?: (number | null);
    air_temp_c_min?: (number | null);
    air_temp_c_max?: (number | null);
    humidity_pct_avg?: (number | null);
    sunlight_hours_avg?: (number | null);
    precipitation_mm_total?: (number | null);
    solar_radiation_mj_m2_day?: (number | null);
};

export type CropCategory = 'leafy' | 'herb' | 'fruiting' | 'other';

export type CropGuidePublic = {
    name_en: string;
    name_tl: string;
    category: CropCategory;
    recommended_setups: string;
    ph_min: number;
    ph_max: number;
    ec_min: number;
    ec_max: number;
    days_to_harvest_min: number;
    days_to_harvest_max: number;
    typical_yield_grams?: (number | null);
    sunlight_hours?: (string | null);
    temperature_day_c?: (string | null);
    temperature_night_c?: (string | null);
    common_issues?: (string | null);
    harvest_indicator?: (string | null);
    image_key?: (string | null);
    source?: (string | null);
    image_url?: (string | null);
    ec_seedling?: (number | null);
    ec_vegetative?: (number | null);
    ec_mature?: (number | null);
    ec_fruiting?: (number | null);
    water_temp_c?: (string | null);
    humidity_pct?: (string | null);
    growlight_hours?: (string | null);
    local_price_php_per_kg_min?: (number | null);
    local_price_php_per_kg_max?: (number | null);
    tips?: (Array<(string)> | null);
    risks?: (Array<{
    [key: string]: unknown;
}> | null);
    growth_stages?: (Array<{
    [key: string]: unknown;
}> | null);
    phases?: (Array<(string)> | null);
    id: string;
};

export type CropGuidesPublic = {
    data: Array<CropGuidePublic>;
    count: number;
};

export type CropStatsRecomputeResponse = {
    updated_fields: number;
};

export type CropStatsResponse = {
    stats: {
        [key: string]: CropStatValue;
    };
};

export type CropStatValue = {
    min: number;
    max: number;
    avg: number;
};

export type Dashboard = {
    gross_current_month: number;
    gross_last_90_days: number;
    gross_ytd: number;
    cogs_current_month: number;
    cogs_last_90_days: number;
    cogs_ytd: number;
    net_margin_pct: number;
    top_crops: Array<{
        [key: string]: unknown;
    }>;
    channel_revenue: Array<{
        [key: string]: unknown;
    }>;
};

export type ExpiryStatus = 'ok' | 'warning' | 'expired';

export type GuideCategory = 'setup' | 'nutrition' | 'business' | 'safety' | 'operations' | 'other';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InventoryCategory = 'seeds' | 'media' | 'nutrients' | 'equipment' | 'packaging' | 'other';

export type InventoryItemCreate = {
    name: string;
    category: InventoryCategory;
    unit: InventoryUnit;
    current_stock?: number;
    low_stock_threshold?: number;
    unit_cost?: (number | null);
    expiry_date?: (string | null);
    notes?: (string | null);
};

export type InventoryItemPublic = {
    name: string;
    category: InventoryCategory;
    unit: InventoryUnit;
    current_stock?: number;
    low_stock_threshold?: number;
    unit_cost?: (number | null);
    expiry_date?: (string | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    is_low_stock?: boolean;
    expiry_status?: ExpiryStatus;
    days_until_expiry?: (number | null);
    last_restocked_at?: (string | null);
};

export type InventoryItemsPublic = {
    data: Array<InventoryItemPublic>;
    count: number;
};

export type InventoryItemUpdate = {
    name?: (string | null);
    category?: (InventoryCategory | null);
    unit?: (InventoryUnit | null);
    low_stock_threshold?: (number | null);
    unit_cost?: (number | null);
    expiry_date?: (string | null);
    notes?: (string | null);
};

export type InventoryUnit = 'grams' | 'pieces' | 'liters' | 'milliliters';

export type LibraryGuidePublic = {
    title: string;
    summary: string;
    category: GuideCategory;
    body_md: string;
    image_key?: (string | null);
    image_url?: (string | null);
    read_time_min?: (number | null);
    tags?: (Array<(string)> | null);
    source?: (string | null);
    id: string;
};

export type LibraryGuidesPublic = {
    data: Array<LibraryGuidePublic>;
    count: number;
};

export type LibraryPestPublic = {
    name: string;
    kind: PestKind;
    severity: PestSeverity;
    affected_crops?: (Array<(string)> | null);
    symptoms?: (Array<(string)> | null);
    causes?: (Array<(string)> | null);
    prevention?: (Array<(string)> | null);
    treatment?: (Array<(string)> | null);
    image_key?: (string | null);
    image_url?: (string | null);
    source?: (string | null);
    id: string;
};

export type LibraryPestsPublic = {
    data: Array<LibraryPestPublic>;
    count: number;
};

export type Message = {
    message: string;
};

export type Milestone = 'Sowed' | 'Germinated' | 'SeedLeaves' | 'TrueLeaves' | 'Transplanted' | 'Vegetative' | 'Flowering' | 'FruitSet' | 'HarvestReady' | 'Harvested' | 'Failed';

export type MovementCreate = {
    movement_type: MovementType;
    quantity: number;
    cost_total?: (number | null);
    related_batch_id?: (string | null);
    notes?: (string | null);
    occurred_at?: (string | null);
};

export type MovementPublic = {
    id: string;
    item_id: string;
    movement_type: MovementType;
    quantity: number;
    cost_total?: (number | null);
    related_batch_id?: (string | null);
    occurred_at: string;
    notes?: (string | null);
};

export type MovementType = 'restock' | 'consume' | 'adjust';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OverheadCreate = {
    category: string;
    monthly_cost: number;
    effective_from?: (string | null);
};

export type OverheadPublic = {
    id: string;
    category: string;
    monthly_cost: number;
    effective_from: string;
};

export type PaymentStatus = 'paid' | 'pending' | 'cancelled';

export type PermissionPublic = {
    id: string;
    name: string;
    resource: string;
    action: string;
    description?: (string | null);
    created_at?: (string | null);
};

export type PermissionsPublic = {
    data: Array<PermissionPublic>;
    count: number;
};

export type PestKind = 'pest' | 'disease' | 'deficiency';

export type PestSeverity = 'low' | 'medium' | 'high';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProduceCreate = {
    name: string;
    quantity?: number;
    unit?: string;
    harvested_at: string;
    expiry_date?: (string | null);
    selling_price?: (number | null);
    notes?: (string | null);
    source_batch_id?: (string | null);
};

export type ProduceMovementCreate = {
    movement_type: ProduceMovementType;
    quantity: number;
    notes?: (string | null);
};

export type ProduceMovementPublic = {
    id: string;
    produce_id: string;
    movement_type: ProduceMovementType;
    quantity: number;
    related_sale_id?: (string | null);
    occurred_at: string;
    notes?: (string | null);
};

export type ProduceMovementsPublic = {
    data: Array<ProduceMovementPublic>;
    count: number;
};

export type ProduceMovementType = 'harvest' | 'reserve' | 'sell' | 'discard' | 'adjust';

export type ProducePublic = {
    name: string;
    quantity?: number;
    unit?: string;
    harvested_at: string;
    expiry_date?: (string | null);
    selling_price?: (number | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    source_batch_id?: (string | null);
    status?: ProduceStatus;
    expiry_status?: ExpiryStatus;
    days_until_expiry?: (number | null);
    created_at: string;
};

export type ProducesPublic = {
    data: Array<ProducePublic>;
    count: number;
};

export type ProduceStatus = 'ready' | 'reserved' | 'sold';

export type ProduceUpdate = {
    name?: (string | null);
    quantity?: (number | null);
    unit?: (string | null);
    status?: (ProduceStatus | null);
    expiry_date?: (string | null);
    selling_price?: (number | null);
    notes?: (string | null);
};

export type RecurFreq = 'none' | 'daily' | 'weekly' | 'monthly';

export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    created_at?: (string | null);
};

export type RolesPublic = {
    data: Array<RolePublic>;
    count: number;
};

export type SaleChannel = 'direct' | 'market' | 'delivery' | 'resto' | 'other';

export type SaleCreate = {
    buyer_label?: (string | null);
    channel?: SaleChannel;
    sold_at?: (string | null);
    payment_status?: PaymentStatus;
    notes?: (string | null);
    items: Array<SaleItemInput>;
};

export type SaleDetail = {
    id: string;
    owner_id: string;
    buyer_label?: (string | null);
    channel: SaleChannel;
    sold_at: string;
    payment_status: PaymentStatus;
    notes?: (string | null);
    items?: Array<SaleItemPublic>;
};

export type SaleItemInput = {
    crop_name: string;
    quantity: number;
    unit?: string;
    unit_price: number;
    linked_batch_id?: (string | null);
};

export type SaleItemPublic = {
    id: string;
    crop_name: string;
    quantity: number;
    unit: string;
    unit_price: number;
    linked_batch_id?: (string | null);
};

export type SalesPublic = {
    data: Array<SaleDetail>;
    count: number;
};

export type SetupCreate = {
    name: string;
    type: SetupType;
    slot_count: number;
    location_label?: (string | null);
    notes?: (string | null);
    installed_at?: (string | null);
};

export type SetupDetail = {
    name: string;
    type: SetupType;
    slot_count: number;
    location_label?: (string | null);
    notes?: (string | null);
    installed_at?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    archived_at?: (string | null);
    primary_photo_url?: (string | null);
    slots?: Array<SetupSlotPublic>;
    photos?: Array<SetupPhotoPublic>;
};

export type SetupPhotoCreate = {
    storage_url: string;
};

export type SetupPhotoPublic = {
    id: string;
    storage_url: string;
    uploaded_at: string;
};

export type SetupPublic = {
    name: string;
    type: SetupType;
    slot_count: number;
    location_label?: (string | null);
    notes?: (string | null);
    installed_at?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    archived_at?: (string | null);
    primary_photo_url?: (string | null);
};

export type SetupSlotPublic = {
    id: string;
    slot_code: string;
    position_index: number;
    status: SlotStatus;
    batch_id?: (string | null);
};

export type SetupsPublic = {
    data: Array<SetupPublic>;
    count: number;
};

export type SetupType = 'DFT' | 'NFT' | 'DutchBucket' | 'Kratky' | 'SNAP';

export type SetupUpdate = {
    name?: (string | null);
    type?: (SetupType | null);
    slot_count?: (number | null);
    location_label?: (string | null);
    notes?: (string | null);
    installed_at?: (string | null);
    archived_at?: (string | null);
};

export type SlotStatus = 'empty' | 'planted' | 'growing' | 'ready';

export type TargetType = 'setup' | 'batch' | 'inventory_item' | 'produce' | 'sale' | 'overhead';

export type TaskCreate = {
    title: string;
    body?: (string | null);
    priority?: TaskPriority;
    due_at?: (string | null);
    recur_freq?: RecurFreq;
    recur_interval?: number;
};

export type TaskPriority = 'high' | 'medium' | 'low' | 'none';

export type TaskPublic = {
    title: string;
    body?: (string | null);
    priority?: TaskPriority;
    due_at?: (string | null);
    recur_freq?: RecurFreq;
    recur_interval?: number;
    id: string;
    owner_id: string;
    completed_at?: (string | null);
    last_completed_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskUpdate = {
    title?: (string | null);
    body?: (string | null);
    priority?: (TaskPriority | null);
    due_at?: (string | null);
    recur_freq?: (RecurFreq | null);
    recur_interval?: (number | null);
};

export type TenantPublic = {
    id: string;
    name: string;
    slug: string;
    is_active: boolean;
    created_at?: (string | null);
};

export type TenantsPublic = {
    data: Array<TenantPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    tier?: UserTier;
    locale?: string;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    tier?: UserTier;
    locale?: string;
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserTier = 'free' | 'grower' | 'pro';

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    tier?: UserTier;
    locale?: string;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    locale?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VisionOnboardRequest = {
    image_url: string;
};

export type VisionOnboardResponse = {
    setup_type: string;
    estimated_slot_count: number;
    layout_hint: string;
    confidence: number;
};

export type ActivityListActivityData = {
    limit?: number;
    skip?: number;
};

export type ActivityListActivityResponse = (ActivitiesPublic);

export type BatchesListBatchesData = {
    includeArchived?: boolean;
    limit?: number;
    setupId?: (string | null);
    skip?: number;
};

export type BatchesListBatchesResponse = (BatchesPublic);

export type BatchesCreateBatchData = {
    requestBody: BatchCreate;
};

export type BatchesCreateBatchResponse = (BatchPublic);

export type BatchesReadBatchData = {
    id: string;
};

export type BatchesReadBatchResponse = (BatchDetail);

export type BatchesUpdateBatchData = {
    id: string;
    requestBody: BatchUpdate;
};

export type BatchesUpdateBatchResponse = (BatchPublic);

export type BatchesDeleteBatchData = {
    id: string;
};

export type BatchesDeleteBatchResponse = (Message);

export type BatchesAllocateSlotsData = {
    id: string;
    requestBody: BatchAllocateSlots;
};

export type BatchesAllocateSlotsResponse = (BatchPublic);

export type BatchesArchiveBatchData = {
    id: string;
};

export type BatchesArchiveBatchResponse = (BatchPublic);

export type BatchesCreateTransitionData = {
    id: string;
    requestBody: BatchTransitionCreate;
};

export type BatchesCreateTransitionResponse = (BatchTransitionPublic);

export type BatchesListTransitionsData = {
    id: string;
    limit?: number;
};

export type BatchesListTransitionsResponse = (Array<BatchTransitionPublic>);

export type BatchesStateCountsData = {
    id: string;
};

export type BatchesStateCountsResponse = (Array<BatchStateCountPublic>);

export type BatchesCreateHarvestData = {
    id: string;
    requestBody: BatchHarvestCreate;
};

export type BatchesCreateHarvestResponse = (BatchHarvestPublic);

export type BatchesListHarvestsData = {
    id: string;
};

export type BatchesListHarvestsResponse = (Array<BatchHarvestPublic>);

export type ChecklistGetChecklistResponse = (unknown);

export type ClimateGetProvidersResponse = ({
    [key: string]: Array<(string)>;
});

export type ClimateGetNormalsData = {
    lat: number;
    lon: number;
    month: number;
    /**
     * open_meteo | nasa_power
     */
    provider?: (string | null);
};

export type ClimateGetNormalsResponse = (ClimateNormals);

export type CropsListCropsData = {
    category?: (CropCategory | null);
    limit?: number;
    query?: (string | null);
    skip?: number;
};

export type CropsListCropsResponse = (CropGuidesPublic);

export type CropsReadCropStatsResponse = (CropStatsResponse);

export type CropsRecomputeCropStatsResponse = (CropStatsRecomputeResponse);

export type CropsReadCropData = {
    id: string;
};

export type CropsReadCropResponse = (CropGuidePublic);

export type CropsSeedCropsResponse = ({
    [key: string]: unknown;
});

export type HydroAiChatData = {
    requestBody: ChatRequest;
};

export type HydroAiChatResponse = (ChatResponse);

export type HydroAiQuotaResponse = ({
    [key: string]: unknown;
});

export type HydroAiVisionSetupOnboardData = {
    requestBody: VisionOnboardRequest;
};

export type HydroAiVisionSetupOnboardResponse = (VisionOnboardResponse);

export type HydroCommonPhotoUploadData = {
    formData: Body_hydro_common_photo_upload;
};

export type HydroCommonPhotoUploadResponse = (unknown);

export type InventoryListItemsData = {
    category?: (InventoryCategory | null);
    limit?: number;
    skip?: number;
};

export type InventoryListItemsResponse = (InventoryItemsPublic);

export type InventoryCreateItemData = {
    requestBody: InventoryItemCreate;
};

export type InventoryCreateItemResponse = (InventoryItemPublic);

export type InventoryReadItemData = {
    id: string;
};

export type InventoryReadItemResponse = (InventoryItemPublic);

export type InventoryUpdateItemData = {
    id: string;
    requestBody: InventoryItemUpdate;
};

export type InventoryUpdateItemResponse = (InventoryItemPublic);

export type InventoryDeleteItemData = {
    id: string;
};

export type InventoryDeleteItemResponse = (Message);

export type InventoryCreateMovementData = {
    id: string;
    requestBody: MovementCreate;
};

export type InventoryCreateMovementResponse = (MovementPublic);

export type InventoryListMovementsData = {
    id: string;
    limit?: number;
};

export type InventoryListMovementsResponse = (Array<MovementPublic>);

export type LibraryGuidesListGuidesData = {
    category?: (GuideCategory | null);
    limit?: number;
    query?: (string | null);
    skip?: number;
};

export type LibraryGuidesListGuidesResponse = (LibraryGuidesPublic);

export type LibraryGuidesReadGuideData = {
    id: string;
};

export type LibraryGuidesReadGuideResponse = (LibraryGuidePublic);

export type LibraryGuidesSeedGuidesResponse = ({
    [key: string]: unknown;
});

export type LibraryPestsListPestsData = {
    kind?: (PestKind | null);
    limit?: number;
    query?: (string | null);
    skip?: number;
};

export type LibraryPestsListPestsResponse = (LibraryPestsPublic);

export type LibraryPestsReadPestData = {
    id: string;
};

export type LibraryPestsReadPestResponse = (LibraryPestPublic);

export type LibraryPestsSeedPestsResponse = ({
    [key: string]: unknown;
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PaymongoCheckoutData = {
    requestBody: CheckoutRequest;
};

export type PaymongoCheckoutResponse = (CheckoutResponse);

export type PaymongoWebhookData = {
    paymongoSignature?: (string | null);
};

export type PaymongoWebhookResponse = ({
    [key: string]: unknown;
});

export type PermissionsReadPermissionsData = {
    limit?: number;
    skip?: number;
};

export type PermissionsReadPermissionsResponse = (PermissionsPublic);

export type PermissionsReadPermissionData = {
    permissionId: string;
};

export type PermissionsReadPermissionResponse = (PermissionPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProduceListProduceData = {
    limit?: number;
    nearExpiry?: boolean;
    skip?: number;
    status?: (ProduceStatus | null);
};

export type ProduceListProduceResponse = (ProducesPublic);

export type ProduceCreateProduceData = {
    requestBody: ProduceCreate;
};

export type ProduceCreateProduceResponse = (ProducePublic);

export type ProduceNearExpiryData = {
    limit?: number;
    skip?: number;
};

export type ProduceNearExpiryResponse = (ProducesPublic);

export type ProduceReadProduceData = {
    id: string;
};

export type ProduceReadProduceResponse = (ProducePublic);

export type ProduceUpdateProduceData = {
    id: string;
    requestBody: ProduceUpdate;
};

export type ProduceUpdateProduceResponse = (ProducePublic);

export type ProduceDeleteProduceData = {
    id: string;
};

export type ProduceDeleteProduceResponse = (Message);

export type ProduceCreateMovementData = {
    id: string;
    requestBody: ProduceMovementCreate;
};

export type ProduceCreateMovementResponse = (ProduceMovementPublic);

export type ProduceListMovementsData = {
    id: string;
    limit?: number;
};

export type ProduceListMovementsResponse = (ProduceMovementsPublic);

export type RolesReadRolesData = {
    limit?: number;
    skip?: number;
};

export type RolesReadRolesResponse = (RolesPublic);

export type RolesReadRoleData = {
    roleId: string;
};

export type RolesReadRoleResponse = (RolePublic);

export type SalesListSalesData = {
    limit?: number;
    skip?: number;
};

export type SalesListSalesResponse = (SalesPublic);

export type SalesCreateSaleData = {
    requestBody: SaleCreate;
};

export type SalesCreateSaleResponse = (SaleDetail);

export type SalesDeleteSaleData = {
    id: string;
};

export type SalesDeleteSaleResponse = (Message);

export type SalesListOverheadsResponse = (Array<OverheadPublic>);

export type SalesAddOverheadData = {
    requestBody: OverheadCreate;
};

export type SalesAddOverheadResponse = (OverheadPublic);

export type SalesDashboardResponse = (Dashboard);

export type SalesExportCsvResponse = (string);

export type SetupsListSetupsData = {
    includeArchived?: boolean;
    limit?: number;
    skip?: number;
};

export type SetupsListSetupsResponse = (SetupsPublic);

export type SetupsCreateSetupData = {
    requestBody: SetupCreate;
};

export type SetupsCreateSetupResponse = (SetupPublic);

export type SetupsReadSetupData = {
    id: string;
};

export type SetupsReadSetupResponse = (SetupDetail);

export type SetupsUpdateSetupData = {
    id: string;
    requestBody: SetupUpdate;
};

export type SetupsUpdateSetupResponse = (SetupPublic);

export type SetupsDeleteSetupData = {
    id: string;
};

export type SetupsDeleteSetupResponse = (Message);

export type SetupsArchiveSetupData = {
    id: string;
};

export type SetupsArchiveSetupResponse = (SetupPublic);

export type SetupsUnarchiveSetupData = {
    id: string;
};

export type SetupsUnarchiveSetupResponse = (SetupPublic);

export type SetupsListSlotsData = {
    id: string;
};

export type SetupsListSlotsResponse = (Array<SetupSlotPublic>);

export type SetupsListPhotosData = {
    id: string;
};

export type SetupsListPhotosResponse = (Array<SetupPhotoPublic>);

export type SetupsAddPhotoData = {
    id: string;
    requestBody: SetupPhotoCreate;
};

export type SetupsAddPhotoResponse = (SetupPhotoPublic);

export type TasksListTasksData = {
    dueBefore?: (string | null);
    includeCompleted?: boolean;
    limit?: number;
    skip?: number;
};

export type TasksListTasksResponse = (TasksPublic);

export type TasksCreateTaskData = {
    requestBody: TaskCreate;
};

export type TasksCreateTaskResponse = (TaskPublic);

export type TasksGetTaskData = {
    taskId: string;
};

export type TasksGetTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksDeleteTaskData = {
    taskId: string;
};

export type TasksDeleteTaskResponse = (Message);

export type TasksCompleteTaskData = {
    taskId: string;
};

export type TasksCompleteTaskResponse = (TaskPublic);

export type TasksUncompleteTaskData = {
    taskId: string;
};

export type TasksUncompleteTaskResponse = (TaskPublic);

export type TenantsReadTenantsData = {
    limit?: number;
    skip?: number;
};

export type TenantsReadTenantsResponse = (TenantsPublic);

export type TenantsReadTenantData = {
    tenantId: string;
};

export type TenantsReadTenantResponse = (TenantPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);